language: java

jdk: oraclejdk11

before_install:
  - chmod +x gradlew

script:
  - ./gradlew check jacocoTestCoverageVerification

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - ./gradlew jacocoTestReport coveralls

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: ybA08toJmMJ8V7u9TLvVSY8RPAmkVV5EULt3GqWBpPIu/dQU0J4L25yEBycNNzzvdHLKJ5r4Hp0kytFGsQ9uWStryxeQnuk5UIoQEExtHXo9MlF+DO+hiZAM/HqBr5xRXD2K8ULuQZfsCt9kkiByO7FNyfhubv90SU2AE3k+JsGLTafEik4Syd4pR9/Iao8tRSZmxpwDIveil7YSh5bz9gIzrO+Q0/3e0gAQlRl6U5Au9+z8ZmkWIPIF02G6wF+Cz7TJiY2/VrKXbY2YhhphSGerV0ztsTTeYO77zTOcxUpB6kiO3GWQtaU/l7i8XeoNNCaNei4fMcbL72sFnu+Biy9xwjZu7P7ljLoFcTrbeTBGrKX1r7RJpDCUUsoBOw+s60PqaPz+1tHYfD7eX/lpg2gOCCJpOmCxyb17CtecEZexPADENnpPvziGHA5unLpaeHCx+/2qwD3pNvRpwe4bSnTuHPJiDSgRWS0NhWwZTqlzNzMebpOnsXi4gyXM5QFwT1Wz41Of2Ll+lo4Cs28pDdMnCdC0b5bvV/fZkwmdoAP8800yDQNpzEUEOc6IX4m9KXMO4EENAvNth2JeqGCz0Ue8/K04WGmeZuGqIBXMGVU2bfDcXZtRxsC8euBdbMDPf5dxEajnWjRLSBWPn3Iwqmix7coiz2WMnxTKkobx5A4=
    file_glob: true
    file: "build/libs/*.jar"
    on:
      tags: true

  - provider: script
    skip_cleanup: true
    script: ./gradlew bintrayUpload
    on:
      tags: true
